Bloggie.Web/Controllers/AddTagsController.cs
using Bloggie.Web;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace MyApp.Namespace
{
    [Authorize(Roles = "Admin")]
    public class AddTagsController : Controller
    {
        
        private readonly ITagRepository _tagRepository;
        public AddTagsController(ITagRepository tagRepository)
        {
            this._tagRepository = tagRepository;
        }
        // GET: AddTagsController
        [Authorize(Roles = "Admin")]
        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Add(AddTagRequests addTagRequests)
        {
            //Mapping the AddTagRequests to Tag Domain Models
            var tag = new Tag
            {
                Name = addTagRequests.Name,
                DisplayName = addTagRequests.DisplayName
            };

            await _tagRepository.AddAsync(tag);
            return RedirectToAction("List");
        }

        [HttpGet]
        [ActionName("List")]
        public async Task<IActionResult> List()
        {
            //Fetching all the tags from the database and passing it to the view
            var allTags = await _tagRepository.GetAllSync();
            return View(allTags);
        }

        [HttpGet]

        public async Task<IActionResult> Edit(Guid id)
        {
            var tag = await _tagRepository.GetAsync(id);
            if (tag != null)
            {
                var editTagRequest = new EditTagRequest
                {
                    Id = tag.Id,
                    Name = tag.Name,
                    DisplayName = tag.DisplayName
                };
                return View(editTagRequest);
            }
            return View(null);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(EditTagRequest editTagRequest)
        {
            //Mapping the EditTagRequest to Tag Domain Models and updating the database
            var tags = new Tag
            {
                Id = editTagRequest.Id,
                Name = editTagRequest.Name,
                DisplayName = editTagRequest.DisplayName
            };

            var updatedTag = await _tagRepository.UpdateAsync(tags);
            if (updatedTag != null)
            {
                //Show Success Message
            }
            else
            {
                //show error message
            }

            
            return RedirectToAction("Edit", new { id = editTagRequest.Id });

        }

        [HttpPost]
        public async Task<IActionResult> Delete(EditTagRequest editTagRequest)
        {

            var deletedTag = await _tagRepository.DeleteAsync(editTagRequest.Id);
            if (deletedTag != null)
            {
                //Show Success Message
                return RedirectToAction("List");
            }
            else
            {
                //show error message
            }

            return View("Edit", new { id = editTagRequest.Id });
        }

    }
}

Bloggie.Web/Controllers/AdminBlogPostController.cs
using Bloggie.Web;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Authorization;

namespace MyApp.Namespace
{
    [Authorize(Roles = "Admin")]
    public class AdminBlogPostController : Controller
    {

        private readonly ITagRepository _tagRepository;
        private readonly IBlogPostRepository _blogPostRepository;
        public AdminBlogPostController(ITagRepository tagRepository, IBlogPostRepository blogPostRepository)

        {
            this._tagRepository = tagRepository;
            this._blogPostRepository = blogPostRepository;
        }

        // GET: AdminBlogPostController
        [HttpGet]
        public async Task<IActionResult> Add()
        {
            var tags = await _tagRepository.GetAllSync();

            var model = new AddBlogPostRequest
            {
                Tags = tags.Select(x => new SelectListItem
                {
                    Text = x.DisplayName,
                    Value = x.Id.ToString()
                })
            };
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Add(AddBlogPostRequest addBlogPostRequest)
        {
            //Mapping the AddBlogPostRequest to BlogPost Domain Models

            var blogPost = new BlogPost
            {
                Heading = addBlogPostRequest.Heading,
                PageTitle = addBlogPostRequest.PageTitle,
                Content = addBlogPostRequest.Content,
                ShortDescription = addBlogPostRequest.ShortDescription,
                FeaturedImageURL = addBlogPostRequest.FeaturedImageURL,
                UrlHandle = addBlogPostRequest.UrlHandle,
                PublishedDate = addBlogPostRequest.PublishedDate,
                Author = addBlogPostRequest.Author,
                IsVisible = addBlogPostRequest.IsVisible
            };

            var selectedTags = new List<Tag>();
            //Adding the selected tags to the blog post
            foreach (var select in addBlogPostRequest.selectedTags)
            {
                var selectecTagGuidId = Guid.Parse(select);
                var exisitingTag = await _tagRepository.GetAsync(selectecTagGuidId);
                if (exisitingTag != null)
                {
                    selectedTags.Add(exisitingTag);
                }

            }
            //mapping the selected tags to the blog post
            blogPost.Tags = selectedTags;

            await _blogPostRepository.AddAsync(blogPost);

            return RedirectToAction("Add");
        }

        [HttpGet]
        public async Task<IActionResult> List()
        {
            var blogPosts = await _blogPostRepository.GetAllSync();
            return View(blogPosts);
        }

        [HttpGet]

        public async Task<IActionResult> Edit(Guid id)
        {

            var getBlogPost = await _blogPostRepository.GetAsync(id);

            var tags = await _tagRepository.GetAllSync();

            //We need to map the BlogPost to EditBlogPostRequest

            if (getBlogPost != null)
            {
                var editBlogPost = new EditBlogPostRequest
                {
                    Id = getBlogPost.Id,
                    Heading = getBlogPost.Heading,
                    PageTitle = getBlogPost.PageTitle,
                    Content = getBlogPost.Content,
                    ShortDescription = getBlogPost.ShortDescription,
                    FeaturedImageURL = getBlogPost.FeaturedImageURL,
                    UrlHandle = getBlogPost.UrlHandle,
                    PublishedDate = getBlogPost.PublishedDate,
                    Author = getBlogPost.Author,
                    IsVisible = getBlogPost.IsVisible,
                    Tags = tags.Select(x => new SelectListItem
                    {
                        Text = x.DisplayName,
                        Value = x.Id.ToString(),
                    }),
                    selectedTags = getBlogPost.Tags.Select(x => x.Id.ToString()).ToArray()

                };

                return View(editBlogPost);
            }


            return View(null);
        }

        [HttpPost]

        public async Task<IActionResult> Edit(EditBlogPostRequest editBlogPostRequest)
        {

            //Mapping the EditBlogPostRequest to BlogPost Domain Models
            var editBlogPost = new BlogPost
            {
                Id = editBlogPostRequest.Id,
                Heading = editBlogPostRequest.Heading,
                PageTitle = editBlogPostRequest.PageTitle,
                Content = editBlogPostRequest.Content,
                ShortDescription = editBlogPostRequest.ShortDescription,
                FeaturedImageURL = editBlogPostRequest.FeaturedImageURL,
                UrlHandle = editBlogPostRequest.UrlHandle,
                PublishedDate = editBlogPostRequest.PublishedDate,
                Author = editBlogPostRequest.Author,
                IsVisible = editBlogPostRequest.IsVisible,

            };

            //Mapping the tags to the domain model

            var selectedTags = new List<Tag>();

            foreach (var selectedTag in editBlogPostRequest.selectedTags)
            {
                if (Guid.TryParse(selectedTag, out var tag))
                {
                    var foundTag = await _tagRepository.GetAsync(tag);

                    if (foundTag != null)
                    {
                        selectedTags.Add(foundTag);
                    }
                }
            }

            editBlogPost.Tags = selectedTags;
            //Submit Information to the repository to update 

            var updateBlogPost = await _blogPostRepository.UpdateAsync(editBlogPost);

            if (updateBlogPost != null)
            {
                return RedirectToAction("List");
            }

            return RedirectToAction("Edit");

        }

        [HttpPost]
        public async Task<IActionResult> Delete(EditBlogPostRequest editBlogPostRequest)
        {
            var deletedBlogPost = await _blogPostRepository.DeleteAsync(editBlogPostRequest.Id);

            if (deletedBlogPost != null)
            {
                return RedirectToAction("List");
            }

            return RedirectToAction("Edit", new { id = editBlogPostRequest.Id });
        }

    }
}

Bloggie.Web/Controllers/AdminUserController.cs
using Bloggie.Web;
using Bloggie.Web.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace MyApp.Namespace
{
    [Authorize(Roles = "Admin")]
    public class AdminUserController : Controller
    {
        // GET: AdminUserController

        private readonly IUserRepository _userRepository;

        public AdminUserController(IUserRepository userRepository)
        {
            this._userRepository = userRepository;
        }

        [HttpGet]
        public async Task<IActionResult> List()
        {
            var users = await _userRepository.GetAllUser();

            if (users != null)
            {
                var userViewModel = new UserViewModel();
                userViewModel.Users = new List<User>();

                foreach (var user in users)
                {
                    userViewModel.Users.Add(new Bloggie.Web.Models.ViewModels.User
                    {
                        Id = Guid.Parse(user.Id),
                        Username = user.UserName,
                        EmailAddress = user.Email

                    });
                }

                return View(userViewModel);
            }

            return View();
        }

    }
}

Bloggie.Web/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity;
@inject SignInManager<IdentityUser> siginInmanager;


<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Bloggie.Web</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Bloggie.Web.styles.css" asp-append-version="true" />
    <link href='https://cdn.jsdelivr.net/npm/froala-editor@latest/css/froala_editor.pkgd.min.css' rel='stylesheet'
        type='text/css' />
    <script type='text/javascript' src='https://cdn.jsdelivr.net/npm/froala-editor@latest/js/froala_editor.pkgd.min.js'>
    </script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow">
            <div class="container">
                using Microsoft.AspNetCore.Identity;
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Bloggie.Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <!--Creating a drop down Nav bar using bootstrap-->
                        @if (siginInmanager.IsSignedIn(User) && User.IsInRole("Admin"))
                        {
                            <li class="nav-item dropdown"></li>
                            <a class="nav-link text-light" href="#" id="navbarDropdown" role="button"
                                data-bs-toggle="dropdown" aria-expanded="false">
                                Admin
                            </a>

                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" asp-area="" asp-controller="AddTags" asp-action="Add">Add
                                        Tag</a></li>
                                <li><a class="dropdown-item" asp-area="" asp-controller="AddTags" asp-action="List">List
                                        Tag</a></li>
                                <li><a class="dropdown-item" asp-area="" asp-controller="AdminBlogPost" asp-action="Add">Add
                                        Blog Post</a></li>
                                <li><a class="dropdown-item" asp-area="" asp-controller="AdminBlogPost"
                                        asp-action="List">List of Blog Post</a></li>

                                <li><a class="dropdown-item" asp-area="" asp-controller="AdminUser"
                                        asp-action="List">List of Users</a></li>
                            </ul>
                        }

                        <div class="d-flex">
                            <!--C# Code to check whether the user is logged in or not based on that we need to display the Buttons-->

                            @if (siginInmanager.IsSignedIn(User))
                            {

                                <div class="me-3 text-light">
                                    @User?.Identity?.Name
                                </div>

                                <a class="btn me-3 bg-light text-dark" asp-area="" asp-controller="Account"
                                    asp-action="Logout">Logout</a>

                            }
                            else
                            {
                                <div class="d-flex">
                                    <a class="btn me-3 bg-light text-dark" asp-area="" asp-controller="Account"
                                        asp-action="Register">
                                        Register</a>

                                    <div class="d-flex">
                                        <a class="btn me-3 bg-light text-dark" asp-area="" asp-controller="Account"
                                            asp-action="Login">
                                            Login
                                        </a>
                                    </div>
                                </div>
                            }

                        </div>
                </div>
            </div>
        </nav>
    </header>
    <div>
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - Bloggie.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>